version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            migrations: true
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:11.1
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./postgres-data:/var/lib/postgresql
# volumes:
#   postgres:
